### ISSUE TITLE
Code to read next page doesn't work on multi-tenant systems

### ISSUE THREAD

**Issue by anobleperson** [cmeerbeek/TA-octopus_deploy#1]
Octopus allows you to have several instances running on the same server.  We have the equivalent of:
https://myserver.com/
and
https://mysever.com/anotherinstance

When paging on the anotherinstance, it fails because the link section returns the instance like so:
```json
"Links": {
    "Self": "/anotherinstance/api/releases",
    "Template": "/anotherinstance/api/releases{?skip,take}",
    "Page.Next": "/anotherinstance/api/releases?skip=30&take=30",
```
The simple append doesn't work because the new request is:
https://myserver.com/anotherinstance/anotherinstance/api/releases?skip=30&take=30

At which point the code throws and in the logs we get:

`ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-octopus_deploy/bin/TA-octopus_deploy.py" ERROR404 Client Error: Not Found`

**Comment by anobleperson** [comment]
I'm not a python dev, so this probably isn't the best way, but I fixed the issue for me with 
```python
import re
...
octopus_url = hostname + \
     re.sub(r'.*/api','/api',json_response['Links']['Page.Next'])
```

**Comment by cmeerbeek** [comment]
I am sorry it took so long but had a very busy period in december. I've added your code and pushed it.
